-- require('spec_helper')

-- describe('llm.ui.views.templates_view', function()
--   local templates_view = require('llm.ui.views.templates_view')

--   before_each(function()
--     vim.ui = {}
--   end)

--   describe('select_template()', function()
--     it('should call vim.ui.select with sorted templates', function()
--       vim.ui.select = spy.new(function() end)
--       local templates = {
--         { name = 'b', description = 'desc b' },
--         { name = 'a', description = 'desc a' }
--       }
--       local callback = function() end

--       templates_view.select_template(templates, callback)

--       assert.spy(vim.ui.select).was.called()
--     end)

--     it('should notify if no templates are found', function()
--       vim.notify = spy.new(function() end)
--       templates_view.select_template({}, function() end)
--       assert.spy(vim.notify).was.called_with('No templates found', vim.log.levels.INFO)
--     end)
--   end)

--   describe('get_user_input()', function()
--     it('should call ui.floating_input', function()
--       local ui = require('llm.core.utils.ui')
--       ui.floating_input = spy.new(function() end)
--       templates_view.get_user_input('prompt', 'default', function() end)
--       assert.spy(ui.floating_input).was.called()
--     end)
--   end)

--   describe('get_input_source()', function()
--     it('should call vim.ui.select', function()
--       vim.ui.select = spy.new(function() end)
--       templates_view.get_input_source(function() end)
--       assert.spy(vim.ui.select).was.called()
--     end)
--   end)

--   describe('get_template_type()', function()
--     it('should call vim.ui.select', function()
--       vim.ui.select = spy.new(function() end)
--       templates_view.get_template_type(function() end)
--       assert.spy(vim.ui.select).was.called()
--     end)
--   end)

--   describe('get_model_choice()', function()
--     it('should call vim.ui.select', function()
--       vim.ui.select = spy.new(function() end)
--       templates_view.get_model_choice(function() end)
--       assert.spy(vim.ui.select).was.called()
--     end)
--   end)

--   describe('select_model()', function()
--     it('should call vim.ui.select', function()
--       vim.ui.select = spy.new(function() end)
--       templates_view.select_model({}, function() end)
--       assert.spy(vim.ui.select).was.called()
--     end)
--   end)

--   describe('get_fragment_choice()', function()
--     it('should call vim.ui.select', function()
--       vim.ui.select = spy.new(function() end)
--       templates_view.get_fragment_choice(function() end)
--       assert.spy(vim.ui.select).was.called()
--     end)
--   end)

--   describe('get_add_fragment_choice()', function()
--     it('should call vim.ui.select', function()
--       vim.ui.select = spy.new(function() end)
--       templates_view.get_add_fragment_choice(function() end)
--       assert.spy(vim.ui.select).was.called()
--     end)
--   end)

--   describe('get_add_system_fragment_choice()', function()
--     it('should call vim.ui.select', function()
--       vim.ui.select = spy.new(function() end)
--       templates_view.get_add_system_fragment_choice(function() end)
--       assert.spy(vim.ui.select).was.called()
--     end)
--   end)

--   describe('get_option_choice()', function()
--     it('should call vim.ui.select', function()
--       vim.ui.select = spy.new(function() end)
--       templates_view.get_option_choice(function() end)
--       assert.spy(vim.ui.select).was.called()
--     end)
--   end)

--   describe('confirm_extract()', function()
--     it('should call ui.floating_confirm', function()
--       local ui = require('llm.core.utils.ui')
--       ui.floating_confirm = spy.new(function() end)
--       templates_view.confirm_extract(function() end)
--       assert.spy(ui.floating_confirm).was.called()
--     end)
--   end)

--   describe('get_schema_choice()', function()
--     it('should call vim.ui.select', function()
--       vim.ui.select = spy.new(function() end)
--       templates_view.get_schema_choice(function() end)
--       assert.spy(vim.ui.select).was.called()
--     end)
--   end)

--   describe('select_schema()', function()
--     it('should call vim.ui.select', function()
--       vim.ui.select = spy.new(function() end)
--       templates_view.select_schema({ { name = 'a' } }, function() end)
--       assert.spy(vim.ui.select).was.called()
--     end)

--     it('should notify if no schemas are found', function()
--       vim.notify = spy.new(function() end)
--       templates_view.select_schema({}, function() end)
--       assert.spy(vim.notify).was.called_with('No schemas found', vim.log.levels.INFO)
--     end)
--   end)

--   describe('confirm_delete()', function()
--     it('should call ui.floating_confirm', function()
--       local ui = require('llm.core.utils.ui')
--       ui.floating_confirm = spy.new(function() end)
--       templates_view.confirm_delete('test', function() end)
--       assert.spy(ui.floating_confirm).was.called()
--     end)
--   end)
-- end)
