name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo add-apt-repository ppa:neovim-ppa/unstable
        sudo apt-get update -y
        sudo apt-get install neovim luarocks -y
        sudo luarocks install busted
        sudo luarocks install luassert
        uv tool install llm

    - name: Run tests
      run: |
        make test
